<?php
  require('questionZero.php');
  require('questionDeux.html');
  require('questionTrois.html');
  require('questionQuatre.php');
  require('questionCinq.html');
  require('questionSix.html');
  require('questionSept.php');
  require('questionHuit.html');
?>